USE PIZZERIA;

insert into customer values (null, "INSTORE", "customer", 000, 0000000, null, null, null, null);

insert into topping values (1, "Pepperoni", 1.25, 0.2, 100, 50);
insert into topping values (2, "Sausage", 1.25, 0.15, 100, 50);
insert into topping values (3, "Ham", 1.5, 0.15, 78, 25);
insert into topping values (4, "Chicken", 1.75, 0.25, 56, 25);
insert into topping values (5, "Green Pepper", 0.5, 0.02, 79, 25);
insert into topping values (6, "Onion", 0.5, 0.02, 85, 25);
insert into topping values (7, "Roma Tomato", 0.75, 0.03, 86, 10);
insert into topping values (8, "Mushrooms", 0.75, 0.1, 52, 50);
insert into topping values (9, "Black Olives", 0.6, 0.1, 39, 25);
insert into topping values (10, "Pineapple", 1, 0.25, 15, 0);
insert into topping values (11, "Jalapenos", 0.5, 0.05, 64, 0);
insert into topping values (12, "Banana Peppers", 0.5, 0.05, 36, 0);
insert into topping values (13, "Regular Cheese", 0.5, 0.12, 250, 50);
insert into topping values (14, "Four Cheese Blend", 1, 0.15, 150, 25);
insert into topping values (15, "Feta Cheese", 1.5, 0.18, 75, 0);
insert into topping values (16, "Goat Cheese", 1.5, 0.2, 54, 0);
insert into topping values (17, "Bacon", 1.5, 0.25, 89, 0);

insert into topping_to_serving values (1, "Small", 2);
insert into topping_to_serving values (1, "Medium", 2.75);
insert into topping_to_serving values (1, "Large", 3.5);
insert into topping_to_serving values (1, "XLarge", 4.5);
insert into topping_to_serving values (2, "Small", 2.5);
insert into topping_to_serving values (2, "Medium", 3);
insert into topping_to_serving values (2, "Large", 3.5);
insert into topping_to_serving values (2, "XLarge", 4.25);
insert into topping_to_serving values (3, "Small", 2);
insert into topping_to_serving values (3, "Medium", 2.5);
insert into topping_to_serving values (3, "Large", 3.25);
insert into topping_to_serving values (3, "XLarge", 4);
insert into topping_to_serving values (4, "Small", 1.5);
insert into topping_to_serving values (4, "Medium", 2);
insert into topping_to_serving values (4, "Large", 2.25);
insert into topping_to_serving values (4, "XLarge", 3);
insert into topping_to_serving values (5, "Small", 1);
insert into topping_to_serving values (5, "Medium", 1.5);
insert into topping_to_serving values (5, "Large", 2);
insert into topping_to_serving values (5, "XLarge", 2.5);
insert into topping_to_serving values (6, "Small", 1);
insert into topping_to_serving values (6, "Medium", 1.5);
insert into topping_to_serving values (6, "Large", 2);
insert into topping_to_serving values (6, "XLarge", 2.75);
insert into topping_to_serving values (7, "Small", 2);
insert into topping_to_serving values (7, "Medium", 3);
insert into topping_to_serving values (7, "Large", 3.5);
insert into topping_to_serving values (7, "XLarge", 4.5);
insert into topping_to_serving values (8, "Small", 1.5);
insert into topping_to_serving values (8, "Medium", 2);
insert into topping_to_serving values (8, "Large", 2.5);
insert into topping_to_serving values (8, "XLarge", 3);
insert into topping_to_serving values (9, "Small", 0.75);
insert into topping_to_serving values (9, "Medium", 1);
insert into topping_to_serving values (9, "Large", 1.5);
insert into topping_to_serving values (9, "XLarge", 2);
insert into topping_to_serving values (10, "Small", 1);
insert into topping_to_serving values (10, "Medium", 1.25);
insert into topping_to_serving values (10, "Large", 1.75);
insert into topping_to_serving values (10, "XLarge", 2);
insert into topping_to_serving values (11, "Small", 0.5);
insert into topping_to_serving values (11, "Medium", 0.75);
insert into topping_to_serving values (11, "Large", 1.25);
insert into topping_to_serving values (11, "XLarge", 1.75);
insert into topping_to_serving values (12, "Small", 0.6);
insert into topping_to_serving values (12, "Medium", 1);
insert into topping_to_serving values (12, "Large", 1.3);
insert into topping_to_serving values (12, "XLarge", 1.75);
insert into topping_to_serving values (13, "Small", 2);
insert into topping_to_serving values (13, "Medium", 3.5);
insert into topping_to_serving values (13, "Large", 5);
insert into topping_to_serving values (13, "XLarge", 7);
insert into topping_to_serving values (14, "Small", 2);
insert into topping_to_serving values (14, "Medium", 3.5);
insert into topping_to_serving values (14, "Large", 5);
insert into topping_to_serving values (14, "XLarge", 7);
insert into topping_to_serving values (15, "Small", 1.75);
insert into topping_to_serving values (15, "Medium", 3);
insert into topping_to_serving values (15, "Large", 4);
insert into topping_to_serving values (15, "XLarge", 5.5);
insert into topping_to_serving values (16, "Small", 1.6);
insert into topping_to_serving values (16, "Medium", 2.75);
insert into topping_to_serving values (16, "Large", 4);
insert into topping_to_serving values (16, "XLarge", 5.5);
insert into topping_to_serving values (17, "Small", 1);
insert into topping_to_serving values (17, "Medium", 1.5);
insert into topping_to_serving values (17, "Large", 2);
insert into topping_to_serving values (17, "XLarge", 3);

insert into base values ("Thin", "Small", 3, 0.5);
insert into base values ("Original", "Small", 3, 0.75);
insert into base values ("Pan", "Small", 3.5, 1);
insert into base values ("Gluten-Free", "Small", 4, 2);
insert into base values ("Thin", "Medium", 5, 1);
insert into base values ("Original", "Medium", 5, 1.5);
insert into base values ("Pan", "Medium", 6, 2.25);
insert into base values ("Gluten-Free", "Medium", 6.25, 3);
insert into base values ("Thin", "Large", 8, 1.25);
insert into base values ("Original", "Large", 8, 2);
insert into base values ("Pan", "Large", 9, 3);
insert into base values ("Gluten-Free", "Large", 9.5, 4);
insert into base values ("Thin", "XLarge", 10, 2);
insert into base values ("Original", "XLarge", 10, 3);
insert into base values ("Pan", "XLarge", 11.5, 4.5);
insert into base values ("Gluten-Free", "XLarge", 12.5, 6);

insert into discount values (1, "Employee", 0.15, NULL);
insert into discount values (2, "Lunch Special Medium", NULL, 1);
insert into discount values (3, "Lunch Special Large", NULL, 2);
insert into discount values (4, "Specialty Pizza", NULL, 1.5);
insert into discount values (5, "Happy Hour", 0.10, NULL);
insert into discount values (6, "Gameday Special", 0.2, NULL);

insert into customer values (NULL, "Andrew", "Wilkes-Krier", 864, 2545861, "115 Party Blvd", "Anderson", "SC", 29621);
insert into customer values (NULL, "Matt", "Engers", 864, 4749953, NULL, NULL, NULL, NULL);
insert into customer values (NULL, "Frank", "Turner", 864, 232844, "6745 Wessex St", "Anderson", "SC", 29621);
insert into customer values (NULL, "Milo", "Auckerman", 864, 8785679, "8879 Suburban Home", "Anderson", "SC", 29621);


insert into anOrder values (NULL, "dinein", true, 20.75, 3.68, "2023-03-05 12:03", 21, NULL, 1);
insert into anOrder values (NULL, "dinein", true, (12.85+6.93), (3.23+1.40), "2023-04-03 12:05", 4, NULL, 1);
insert into anOrder values (NULL, "pickup", true, (6*14.88), (6*3.30), "2023-03-03 21:30", NULL, true, 2);
insert into anOrder values (NULL, "delivery", true, (27.94+31.5+26.75), (9.19+6.25+8.18), "2023-04-20 19:11", NULL, NULL, 2);
insert into anOrder values (NULL, "pickup", true, 27.45, 7.88, "2023-03-02 17:30", NULL, true, 3);
insert into anOrder values (NULL, "delivery", true, 25.81, 4.24, "2023-03-02 18:17", NULL, NULL, 4);
insert into anOrder values (NULL, "delivery", true, (18+19.25), (2.75+3.25), "2023-04-13 20:32", NULL, NULL, 5);


insert into pizza values (NULL, 1, "Thin", "Large", true, 20.75, 3.68);
insert into pizza_to_topping values (1, 1, 1);
insert into pizza_to_topping values (1, 13, 2);
insert into pizza_to_topping values (1, 2, 1);
insert into pizza_to_discount values(1, 3);

insert into pizza values (NULL, 2, "Pan", "Medium", true, 12.85, 3.23);
insert into pizza_to_discount values(2, 3);
insert into pizza_to_discount values(2, 4);
insert into pizza_to_topping values (2, 15, 1);
insert into pizza_to_topping values (2, 9, 1);
insert into pizza_to_topping values (2, 7, 1);
insert into pizza_to_topping values (2, 8, 1);
insert into pizza_to_topping values(2, 12, 1);
insert into pizza values (NULL, 2, "Original", "Small", true, 6.93, 1.4);
insert into pizza_to_topping values (3, 13, 1);
insert into pizza_to_topping values (3, 4, 1);
insert into pizza_to_topping values (3, 12, 1);

insert into pizza values (NULL, 3, "Original", "Large", true, 14.88, 3.3);
insert into pizza_to_topping values (4, 13, 1);
insert into pizza_to_topping values (4, 1, 1);
insert into pizza values (NULL, 3, "Original", "Large", true, 14.88, 3.3);
insert into pizza_to_topping values (5, 13, 1);
insert into pizza_to_topping values (5, 1, 1);
insert into pizza values (NULL, 3, "Original", "Large", true, 14.88, 3.3);
insert into pizza_to_topping values (6, 13, 1);
insert into pizza_to_topping values (6, 1, 1);
insert into pizza values (NULL, 3, "Original", "Large", true, 14.88, 3.3);
insert into pizza_to_topping values (7, 13, 1);
insert into pizza_to_topping values (7, 1, 1);
insert into pizza values (NULL, 3, "Original", "Large", true, 14.88, 3.3);
insert into pizza_to_topping values (8, 13, 1);
insert into pizza_to_topping values (8, 1, 1);
insert into pizza values (NULL, 3, "Original", "Large", true, 14.88, 3.3);
insert into pizza_to_topping values (9, 13, 1);
insert into pizza_to_topping values (9, 1, 1);

insert into pizza values (NULL, 4, "Original", "XLarge", true, 27.94, 9.19);
insert into pizza_to_topping values (10, 1, 1);
insert into pizza_to_topping values (10, 2, 1);
insert into pizza_to_topping values (10, 14, 1);
insert into pizza values (NULL, 4, "Original", "XLarge", true, 31.50, 6.25);
insert into pizza_to_topping values (11, 3, 2);
insert into pizza_to_topping values (11, 10, 2);
insert into pizza_to_topping values (11, 14, 1);
insert into pizza_to_discount values (11, 4);
insert into pizza values (NULL, 4, "Original", "XLarge", true, 26.75, 8.18);
insert into pizza_to_topping values (12, 4, 1);
insert into pizza_to_topping values (12, 17, 1);
insert into pizza_to_topping values (12, 14, 1);
insert into order_to_discount values (4, 6);

insert into pizza values (NULL, 5, "Gluten-Free", "XLarge", true, 27.45, 7.88);
insert into pizza_to_topping values (13, 5, 1);
insert into pizza_to_topping values (13, 6, 1);
insert into pizza_to_topping values (13, 7, 1);
insert into pizza_to_topping values (13, 8, 1);
insert into pizza_to_topping values (13, 9, 1);
insert into pizza_to_topping values (13, 16, 1);
insert into pizza_to_discount values (13, 4);

insert into pizza values (NULL, 6, "Thin", "Large", true, 25.81, 4.24);
insert into pizza_to_topping values (14, 5, 1);
insert into pizza_to_topping values (14, 6, 1);
insert into pizza_to_topping values (14, 4, 1);
insert into pizza_to_topping values (14, 8, 1);
insert into pizza_to_topping values (14, 14, 2);

insert into pizza values (NULL, 7, "Thin", "Large", true, 18, 2.75);
insert into pizza_to_topping values (15, 14, 2);
insert into pizza values (NULL, 7, "Thin", "Large", true, 19.25, 3.25);
insert into pizza_to_topping values (16, 1, 2);
insert into pizza_to_topping values (16, 13, 1);
insert into order_to_discount values(7, 1);